### ISSUE TITLE
File_sharings.json.zip is missing for Snapshot_20231012

### ISSUE THREAD

**Issue by sajedjalil** [NAIST-SE/DevGPT#7]
**ChatGPT_Link_Sharing.csv** contains rows for code file But the **Snapshot_20231012** does not contains any relevant file_sharings.json.zip file.

**Comment by markxiaotao** [comment]
Thank you for leaving a comment. Since the file_sharings.json.zip is larger than 100 MiB, which is a [limit](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github#file-size-limits) of the maximum size of a single file uploading on GitHub. We put the consistent file on the [Zenodo package](https://zenodo.org/records/10009967), as explained in 
https://github.com/NAIST-SE/DevGPT/commit/35d906d957026f3db282b19dcc5074e399010725

**Comment by markxiaotao** [comment]
Now we put these large files on GitHub, which is consistent with the Zenodo package. FYL, we have the update on resolving the empty list of conversations in the new version of [Zenodo package](https://zenodo.org/records/10086809) and [GitHub](https://github.com/NAIST-SE/DevGPT/commit/210bb9455d15f200bf8ffa3f443a2a8228a69cfb).
